### ISSUE TITLE
Requesting MacOSX10.13.SDK from XCode9.4.1.app

### ISSUE THREAD

**Issue by Gcenx** [joseluisq/macosx-sdks#1]
This is the final available SDK that supports 32Bit it would be nice to have a prepackaged version available.

**Comment by joseluisq** [comment]
Sure, I'll see if I can get hold of the SDK for packaging it.

**Comment by Gcenx** [comment]
I’d assumed you were downloading the relevant version of Xcode and running the script to package up the SDK.

Manually packing the SDKs found on GitHub won’t include the relevant C++ headers nor the man pages (and some other items), those are only found within the relevant Xcode.app

**Comment by joseluisq** [comment]
> I’d assumed you were downloading the relevant version of Xcode and running the script to package up the SDK.

Maybe I was misunderstood.
But yeah the method here is essentially _the proper xcode download + packaging using the osxcross script_.

Anyway what I meant was that since I have not a Mac at hand (I use someone else Mac) as soon as I can I could try to package it.

> Manually packing the SDKs found on GitHub won’t include the relevant C++ headers nor the man pages (and some other items), those are only found within the relevant Xcode.app

Yeah, I think you mean those ones like `phracker/MacOSX-SDKs`, right? because [the script used here](https://github.com/tpoechtrager/osxcross/blob/master/tools/gen_sdk_package.sh#L183-L193) look at C++ headers and man pages. Isn't?

**Comment by Gcenx** [comment]
> Maybe I was misunderstood with "get the SDK". I meant xcode. But yeah the method here is essentially _the proper xcode download + packaging with the osxcross script_.

Yeah that’s what I thought due to the mention of SDK, doing that produces useless results.

> Anyway what I meant was that since I have not a Mac at hand (I use someone else Mac) as soon as I can I could try to package it.

Ah ok that makes sense, the version that contains the final build of the SDK is Xcode 9.4.1.

> Yeah, I think you mean those ones like `phracker/MacOSX-SDKs`, right? because [the script used here](https://github.com/tpoechtrager/osxcross/blob/master/tools/gen_sdk_package.sh#L183-L193) looks at C++ headers and man pages. Isn't?

That’s correct Xcode itself contains additional files, on macOS the alternative SDKs would work as the missing files are included within Xcode but when using osxcross those are missing.

**Comment by joseluisq** [comment]
It has taken some time to download, convert the `Xcode.app` into a `Xcode.dmg` because looks like they are only providing `.xip` files (`Xcode_9.4.1.xip`).

```
$ ./tools/gen_sdk_package.sh
found Xcode: /Volumes/Xcode/Xcode.app
packaging MacOSX10.13 SDK (this may take several minutes) ...

-rw-r--r--   1 jq  staff    34M Nov  3 13:00 MacOSX10.13.sdk.tar.xz
```

But anyway here it is [10.13](https://github.com/joseluisq/macosx-sdks/releases/tag/10.13).
Feel free to give it a test.
