### ISSUE TITLE
Older SDKs

### ISSUE THREAD

**Issue by OmniBlade** [joseluisq/macosx-sdks#2]
Could you add older SDKs? I've managed to package the SDKs as old as 10.4u which osxcross theoretically supports as it was the first x86 release. Using the oldest SDK that your software is intended to run on can prevent issues of accidentally using new APIs that don't exist on older versions of the OS as they will get compile time errors on older SDKs.

**Comment by joseluisq** [comment]
I updated the repo to support some way to contribute.
Please have a look at https://github.com/joseluisq/macosx-sdks#contributions

Just let me know if you need any help.

**Comment by joseluisq** [comment]
BTW should this issue be closed or are you planning more SDKs to submit?

**Comment by joseluisq** [comment]
Closing, feel free to open a new issue when needed.
